Struct.PIM.ProductViewer.Website/Controllers/MasterController.cs
using Struct.PIM.ProductViewer.Helpers;
using Struct.PIM.ProductViewer.Website.Helpers;
using Struct.PIM.ProductViewer.Website.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web;
using Umbraco.Web.Mvc;

namespace Struct.PIM.ProductViewer.Website.Controllers
{
    public class MasterController : SurfaceController
    {
        public virtual ActionResult _Header()
        {
            var model = new HeaderModel();
            model.MenuItems = GetCategories();
            return PartialView("PageElements/_Header", model);
        }

        private List<MenuItemModel> GetCategories()
        {
            var categories = ApplicationContext.Application.Services.CategoryService.GetAllCategories(new Guid("4ce9b67b-8632-43bb-8ca8-a71d575353a9"), "en-GB");
            var categoriesByParent = categories.Where(x => x.ParentId != null).GroupBy(x => x?.ParentId).ToDictionary(x => x?.Key, x => x.Select(y => y).ToList());
            var rootCategories = categories.Where(x => x.ParentId == null);
            var menuItems = new List<MenuItemModel>();

            foreach (var category in rootCategories.OrderBy(x => x.SortOrder))
            {
                var groupUrl = string.Format("/{0}/g/{1}", category.Name?.AsSlug() ?? string.Empty, category.CategoryId);
                var menuItem = new MenuItemModel(category.Name, groupUrl);

                if (categoriesByParent.ContainsKey(category.CategoryId))
                {
                    var subMenuItems = new List<MenuItemModel>();

                    foreach (var subGroup in categoriesByParent[category.CategoryId].OrderBy(x => x.SortOrder))
                    {
                        var subGroupUrl = string.Format("/{0}/{1}/g/{2}", category.Name?.AsSlug() ?? string.Empty, subGroup.Name?.AsSlug() ?? string.Empty, subGroup.CategoryId);
                        subMenuItems.Add(new MenuItemModel(subGroup.Name, subGroupUrl));
                    }

                    menuItem.Children = subMenuItems;
                }

                menuItems.Add(menuItem);
            }
            return menuItems;
        }
    }
}

Struct.PIM.ProductViewer.Website/Controllers/MemberController.cs
using Struct.PIM.ProductViewer.Website.Helpers;
using Struct.PIM.ProductViewer.Website.Models;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web.Security;
using Umbraco.Web.Mvc;

namespace Struct.PIM.ProductViewer.Website.Controllers
{
    public class MemberController : SurfaceController
    {
        public ActionResult RenderLogin()
        {
            return PartialView("~/Views/Account/_Login.cshtml", new LoginModel());
        }

        public ActionResult RenderAccountDetails()
        {
            var loggedInUser = Membership.GetUser();
            var member = Services.MemberService.GetByUsername(loggedInUser.UserName);

            return PartialView("~/Views/Account/_AccountDetails.cshtml", new MyAccountModel
            {
                Email = member.Email,
                Name = member.Name,
                UserId = member.Id
            });
        }

        public ActionResult RenderUpdatePassword()
        {
            var loggedInUser = Membership.GetUser();
            var member = Services.MemberService.GetByUsername(loggedInUser.UserName);
            return PartialView("~/Views/Account/_UpdatePassword.cshtml", new UpdatePasswordModel { UserId = member.Id});
        }

        public ActionResult RenderResetPassword()
        {
            return PartialView("~/Views/Account/_ResetPassword.cshtml", new ResetPasswordModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SubmitLogin(LoginModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                if (Membership.ValidateUser(model.Username, model.Password))
                {
                    FormsAuthentication.SetAuthCookie(model.Username, false);
                    UrlHelper myHelper = new UrlHelper(HttpContext.Request.RequestContext);
                    if (myHelper.IsLocalUrl(returnUrl))
                    {
                        return Redirect(returnUrl);
                    }
                    else
                    {
                        return Redirect("~/");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "The username or password provided is incorrect.");
                }
            }
            return CurrentUmbracoPage();
        }

        public ActionResult SubmitLogout()
        {
            TempData.Clear();
            Session.Clear();
            FormsAuthentication.SignOut();
            return RedirectToCurrentUmbracoPage();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SubmitAccountDetails(MyAccountModel model)
        {
            if (ModelState.IsValid)
            {
                var member = Services.MemberService.GetById(model.UserId);
                member.Name = model.Name;
                member.Email = model.Email;
                Services.MemberService.Save(member);
                ModelState.Add(new KeyValuePair<string, ModelState>("AccountSaved", new ModelState()));
            }
            return CurrentUmbracoPage();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdatePassword(UpdatePasswordModel model)
        {
            if (ModelState.IsValid)
            {
                if(model.Password != model.PasswordRepeat)
                {
                    ModelState.AddModelError("", "Passwords were not equal to each other");
                }
                else
                {
                    var member = Services.MemberService.GetById(model.UserId);
                    try
                    {
                        Services.MemberService.SavePassword(member, model.Password);
                        ModelState.Add(new KeyValuePair<string, ModelState>("PasswordUpdated", new ModelState()));
                    }
                    catch (MembershipPasswordException e)
                    {
                        ModelState.AddModelError("", "Password is too weak");
                    }
                }
            }
            return CurrentUmbracoPage();
        }

        public ActionResult ResetPassword(ResetPasswordModel model)
        {
            if (ModelState.IsValid)
            {
                var memberUsername = Membership.GetUserNameByEmail(model.Email);
                var member = Membership.GetUser(memberUsername);
                if (member != null)
                {
                    var password = member.ResetPassword();
                    MailHelper.SendResetPasswordNotification(password, member);
                    return Redirect("~/");
                }
                else
                {
                    ModelState.AddModelError("", "No user with this email was found");
                }
            }
            return CurrentUmbracoPage();
        }
    }
}

Struct.PIM.ProductViewer.Website/Controllers/ProductController.cs
using Struct.PIM.ProductViewer.Entity;
using Struct.PIM.ProductViewer.Website.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Models;
using Umbraco.Web.Mvc;

namespace Struct.PIM.ProductViewer.Website.Controllers
{
    public class ProductController : RenderMvcController
    {
        public ActionResult List(ContentModel contentModel, string friendlyUrl, int? categoryId = null)
        {
            CategoryDocument currentCategory = null;
            if (categoryId.HasValue)
            {
                currentCategory = ApplicationContext.Application.Services.CategoryService.GetCategory(categoryId.Value, "en-GB");
            }

            RequestModel requestModel = RequestModel.ResolveFromQueryString();
            requestModel.CategoryId = categoryId;

            //If request is an AJAX request, we only want to return the inline _List result and not the whole page
            if (Request.IsAjaxRequest() || Request.QueryString["ajax"] == "1")
            {
                return _List(contentModel, requestModel);
            }

            var searchDefinition = requestModel.BuildSearchDefinition();
            var result = ApplicationContext.Application.Services.ProductService.SearchProducts(searchDefinition);

            var resultModel = new ResultModel(requestModel, result);
            var model = new ProductListModel(contentModel.Content);

            if (currentCategory != null)
            {
                var parentCategory = currentCategory.ParentId.HasValue ? ApplicationContext.Application.Services.CategoryService.GetCategory(currentCategory.ParentId.Value, "en-GB") : null;
                MapBreadcrumb(model, currentCategory, parentCategory);
                ViewData["PageTitle"] = model.CurrentCategory.Name;
            }
            model.ListResult = resultModel;
            return View("List", model);
        }

        public virtual ActionResult _List(ContentModel contentModel, RequestModel requestModel)
        {
            var searchDefinition = requestModel.BuildSearchDefinition();
            var result = ApplicationContext.Application.Services.ProductService.SearchProducts(searchDefinition);
            var resultModel = new ResultModel(requestModel, result);
            return PartialView("_List", resultModel);
        }

        public ActionResult Page(ContentModel contentModel, string friendlyUrl, string productId, int? variantId = null)
        {
            var model = new ProductModel(contentModel.Content);
            model.Product = ApplicationContext.Application.Services.ProductService.GetDetailedProduct(productId, "en-GB");

            if (model.Product == null)
            {
                return HttpNotFound();
            }

            if (variantId.HasValue)
            {
                model.Variant = model.Product.Variants.FirstOrDefault(x => x.Id == variantId);
            }
            else if (model.Product.Variants.Any())
            {
                model.Variant = model.Product.DefaultVariantId.HasValue ?
                    model.Product.Variants.FirstOrDefault(x => x.Id == model.Product.DefaultVariantId.Value) :
                    model.Product.Variants.FirstOrDefault();
            }
            ViewData["PageTitle"] = model.Product.Name;
            return View("Page", model);
        }

        public virtual ActionResult Search(ContentModel contentModel)
        {
            var model = new ProductListModel(contentModel.Content);
            RequestModel requestModel = RequestModel.ResolveFromQueryString();
            if (Request.IsAjaxRequest() || Request.QueryString["ajax"] == "1")
            {
                return _List(contentModel, requestModel);
            }
            var searchDefinition = requestModel.BuildSearchDefinition();
            var result = ApplicationContext.Application.Services.ProductService.SearchProducts(searchDefinition);

            var resultModel = new ResultModel(requestModel, result);
            model.IsSearch = true;
            model.ListResult = resultModel;
            model.Query = requestModel.Query;

            return View("List", model);
        }

        public ActionResult RenderHighLightProduct(List<int> productIds)
        {
            var model = ApplicationContext.Application.Services.ProductService.GetProducts(productIds, "en-GB");
            return PartialView("PageElements/_ProductHighLight", model);
        }

        private void MapBreadcrumb(ProductListModel model, CategoryDocument currentCategory, CategoryDocument parentCategory)
        {
            model.CurrentCategory = currentCategory;
            if (parentCategory != null)
            {
                model.Breadcrumb.Add(parentCategory);
            }
        }
    }
}

Struct.PIM.ProductViewer.Website/Views/HomePage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.HomePage>
@using ContentModels = Umbraco.Web.PublishedModels;

@{ Layout = "Master.cshtml"; }

<div class="slider-area">
    @Html.Action("RenderHighLightProduct", "Product", new { productIds = new List<int>{ 25, 20 } });
</div>

Struct.PIM.ProductViewer.Website/Views/Login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.Login> 
@using ContentModels = Umbraco.Web.PublishedModels;

@{ 
    Layout = "LoginMaster.cshtml";     
}

@Html.Action("RenderLogin", "Member")

Struct.PIM.ProductViewer.Website/Views/LoginMaster.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@{
    Layout = "MasterLayout.cshtml";    
}

<main class="main-content-wrap login-wrap">
    <div class="login-form-container">
        <div class="logo-container">
            <img alt="" src="assets/img/logo/logo-dark.png">
        </div>
        @RenderBody()
    </div>
</main>

Struct.PIM.ProductViewer.Website/Views/Master.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@{
    Layout = "MasterLayout.cshtml";
}

<!-- HEADER -->
@Html.Action("_Header", "Master")
<!--// HEADER -->
<!-- MAIN CONTENT -->
<main class="main-content-wrap">

    @RenderBody()

</main>
<!-- // MAIN CONTENT -->
<!-- FOOTER -->
@Html.Partial("PageElements/_Footer")
<script src="~/assets/js/shared.js"></script>
<script src="~/assets/js/cart.js"></script>
@RenderSection("ExtraJs", false)
<!--// FOOTER -->

Struct.PIM.ProductViewer.Website/Views/MasterLayout.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@{
    Layout = null;
}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>
        @if (ViewData["PageTitle"] != null && !string.IsNullOrEmpty(ViewData["PageTitle"].ToString()))
        {
            @ViewData["PageTitle"]
        }
        else
        {
            @Html.Raw("Struct Product Portal");
        }
    </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Favicon -->
    <link rel="icon" href="/assets/img/favicon.png">

    <!-- CSS
    ============================================ -->
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
    <!-- Icon Font CSS -->
    <link rel="stylesheet" href="~/assets/css/icons.min.css">
    <!-- Plugins CSS -->
    <link rel="stylesheet" href="~/assets/css/plugins.css">
    <!-- Main Style CSS -->
    <link rel="stylesheet" href="~/assets/scss/style.css">

    <link rel="stylesheet" href="~/assets/scss/login.min.css">
    <link rel="stylesheet" href="~/assets/scss/productPage.min.css">
</head>
<body>

    @RenderBody()
</body>
</html>

Struct.PIM.ProductViewer.Website/Views/MyAccount.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.MyAccount>
@using ContentModels = Umbraco.Web.PublishedModels;

@{ Layout = "Master.cshtml"; }

<div class="breadcrumb-area pt-35 pb-35 bg-gray-3">
    <div class="container">
        <div class="breadcrumb-content text-center">
            <ul>
                <li>
                    <a href="/">Home</a>
                </li>
                <li class="active">My Account </li>
            </ul>
        </div>
    </div>
</div>

<div class="container mt-100">
    <div class="row">
        <div class="ml-auto mr-auto col-lg-9">
            <div class="checkout-wrapper">
                <div id="account" class="panel-group">

                    @Html.Action("RenderAccountDetails", "Member")

                    @Html.Action("RenderUpdatePassword", "Member")
                </div>
            </div>
        </div>
    </div>
</div>

Struct.PIM.ProductViewer.Website/Views/ResetPassword.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.ResetPassword>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
    Layout = "LoginMaster.cshtml";
}

@Html.Action("RenderResetPassword", "Member")